const contractConstants = {
    REQUEST_CONTRACTS: 'REQUEST_CONTRACTS',
    REQUEST_CONTRACTS_SUCCESS: 'REQUEST_CONTRACTS_SUCCESS',
    REQUEST_CONTRACTS_FAILURE: 'REQUEST_CONTRACTS_FAILURE',
};
export default contractConstants;
