const walletConnectConstants = {
    UPDATE_CONNECTOR: 'UPDATE_CONNECTOR',
    UPDATE_ADDRESS: 'UPDATE_ADDRESS',
    UPDATE_ACCOUNTS: 'UPDATE_ACCOUNTS',
    UPDATE_CHAIN: 'UPDATE_CHAIN',
    UPDATE_ASSETS: 'UPDATE_ASSETS',
    UPDATE_DATA: 'UPDATE_DATA',
    RESET: 'RESET',
    DEPLOY_CHANGE: 'DEPLOY_CHANGE',
};
export default walletConnectConstants;
